### ISSUE TITLE
make ./gameboy failed

### ISSUE THREAD

**Issue by bei-startdt** [krocki/gb#3]
~/tmp_git_clone/gb on  master! ⌚ 10:26:40
$ make         
gcc -Ofast -fPIC -c main_lcd.c -o main_lcd.o
main_lcd.c:6:10: fatal error: GLFW/glfw3.h: No such file or directory
 #include <GLFW/glfw3.h>
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:23: recipe for target 'main_lcd.o' failed
make: *** [main_lcd.o] Error 1

make ./gameboy failed...

further more, as a new python env, pip pkg need numpy CFFI scipy pillow in your project.

**Comment by krocki** [comment]
For running the python wrapper it is sufficient to run: ‘make gameboy.so’ which will produce the shared library only without OpenGL stuff. It should be possible to use the python interface only with cffi and numpy installed. Pillow and scipy are used for image resizing only
